[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
alphado_reward = "7yUhyypH3qAd7KTKpa31AKAv5bEbLtVL5Wf53QSemRvA"

[programs.devnet]
alphado_reward = "7yUhyypH3qAd7KTKpa31AKAv5bEbLtVL5Wf53QSemRvA"

[programs.mainnet]
alphado_reward = "7yUhyypH3qAd7KTKpa31AKAv5bEbLtVL5Wf53QSemRvA"

[registry]
url = " https://api.mainnet-beta.solana.com"

[provider]
cluster = "mainnet"
wallet = "~/Projects/solana/its_production.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
